/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/mfa/codigos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Genera los códigos de recuperación del segundo factor */
        post: operations["AutenticacionController_generarCodigos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/recuperacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retira el factor perdido con un código de recuperación */
        post: operations["AutenticacionController_recuperarFactor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/restablecimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra en auditoría el restablecimiento de la propia contraseña */
        post: operations["AutenticacionController_registrarRestablecimiento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identidad y alcance del token presentado */
        get: operations["AutenticacionController_sesion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enumera las copropiedades que el token alcanza, y solo esas */
        get: operations["CopropiedadesController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/ingesta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ruta de identidad de servicio: valida el tenant en la aplicación */
        post: operations["CopropiedadesController_ingerir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lee una copropiedad dentro del alcance del token */
        get: operations["CopropiedadesController_leer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alertas abiertas y en atención, con su cumplimiento de KPI-25 */
        get: operations["AlertasController_abiertas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/alertas/{alertaId}/atencion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** El operador toma la alerta; queda atribuida a él */
        post: operations["AlertasController_atender"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/alertas/{alertaId}/resolucion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la alerta; las notas son obligatorias */
        post: operations["AlertasController_resolver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/autorizaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autorizaciones activas o historial completo (HU-16, HU-17) */
        get: operations["AutorizacionesController_listar"];
        put?: never;
        /** Crea una autorización, única o recurrente (HU-07, HU-09, RN-22) */
        post: operations["AutorizacionesController_crearAutorizacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/autorizaciones/{autorizacionId}/acompanantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Añade un acompañante por su propia identidad (HU-08, D-01) */
        post: operations["AutorizacionesController_agregarAcompanante"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/autorizaciones/{autorizacionId}/revocacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoca con motivo obligatorio; no borra (HU-10, RN-19) */
        post: operations["AutorizacionesController_revocar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/biometria/barrido": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Supresión de las vencidas y retirada de terminales (RN-11, KPI-21) */
        post: operations["BiometriaController_ejecutarBarrido"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/biometria/capturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Valida la calidad y solicita el consentimiento al TITULAR (CU-02, CA-08) */
        post: operations["BiometriaController_capturarRostro"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/biometria/consentimientos/{consentimientoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de un consentimiento, sin dato biométrico alguno */
        get: operations["BiometriaController_verConsentimiento"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/biometria/consentimientos/{consentimientoId}/respuesta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** El TITULAR acepta o rechaza. Nadie responde por él (RN-10) */
        post: operations["BiometriaController_responderConsentimiento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/biometria/consentimientos/{consentimientoId}/revocacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revocación del titular: supresión inmediata (RN-11, CA-11) */
        post: operations["BiometriaController_revocarConsentimiento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/biometria/plantillas/{plantillaId}/sincronizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Empuja la plantilla a una terminal, si hay consentimiento (RN-09) */
        post: operations["BiometriaController_sincronizarPlantilla"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/dispositivos/pendientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Equipos con una orden sin ejecutar (se muestran «sincronizando») */
        get: operations["DispositivosController_pendientes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/dispositivos/{dispositivoId}/configuracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encola la reconfiguración del equipo, atribuida a quien la pide */
        post: operations["DispositivosController_configurar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/dispositivos/{dispositivoId}/reinicio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encola el reinicio del equipo; queda auditado quién lo ordenó */
        post: operations["DispositivosController_reiniciar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/dispositivos/{dispositivoId}/sincronizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encola la sincronización de plantillas y reglas del equipo */
        post: operations["DispositivosController_sincronizar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial filtrado y paginado por cursor (HU-32) */
        get: operations["EventosController_historial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/eventos/exportacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporta el historial en CSV, Excel o PDF (HU-32) */
        get: operations["EventosController_exportacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/eventos/flujo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flujo de eventos y alertas en vivo (SSE) */
        get: operations["EventosController_flujo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/eventos/{eventoId}/evidencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** URL firmada de vida corta a la evidencia (RN-21) */
        get: operations["EventosController_urlDeEvidencia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/informes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vista previa y frecuencia semanal de los cuatro informes (HU-32) */
        get: operations["InformesController_generar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/padron/vehiculos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vehículos con su vivienda y su propietario (HU-04, HU-05) */
        get: operations["PadronDeCopropiedadController_vehiculos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/padron/viviendas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Directorio de viviendas con totales de activas e inactivas (HU-01, RN-13) */
        get: operations["PadronDeCopropiedadController_viviendas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/tablero/accesos-por-hora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histograma de accesos del día en la zona de la copropiedad */
        get: operations["TableroController_leerAccesosPorHora"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/tablero/dispositivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado en línea de los dispositivos por su latido (CA-26, RN-12) */
        get: operations["TableroController_leerDispositivos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/tablero/indicadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Las cuatro tarjetas de indicadores del tablero (HU-38) */
        get: operations["TableroController_leerIndicadores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/zonas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zonas con su aforo y su disponibilidad de ahora mismo (HU-19) */
        get: operations["ZonasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/zonas/{zonaId}/autorizaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Da permiso sobre la zona a una autorización (HU-19, HU-20) */
        post: operations["ZonasController_permiso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/zonas/{zonaId}/configuracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Configura horario, aforo, normas y apertura de la zona (HU-18) */
        post: operations["ZonasController_configuracion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/zonas/{zonaId}/ingresos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ocupa una plaza; el aforo lo garantiza la base (CU-05, CA-14, CA-15) */
        post: operations["ZonasController_ingreso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copropiedades/{id}/zonas/{zonaId}/salidas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Libera una plaza; nunca baja de cero (CU-05 6a) */
        post: operations["ZonasController_salida"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El proceso está vivo */
        get: operations["SaludController_salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingesta/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recibe un evento firmado del Alarm Server, lo decide y lo registra
         * @description Exige firma HMAC vigente. Registra el evento en el histórico inmutable, clasifica y escala la alerta si procede, y deduplica por clave de idempotencia (RN-02, RN-03, RN-17, CA-22).
         */
        post: operations["IngestaController_recibir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingesta/latidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra el latido de un dispositivo (CA-26) */
        post: operations["IngestaController_latido"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/padron/carga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Carga transaccional desde CSV con reporte de errores por fila (HU-03) */
        post: operations["PadronController_cargar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/padron/carga/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Carga transaccional desde XLSX validando el TIPO REAL del archivo (HU-03, D-20t) */
        post: operations["PadronController_cargarXlsx"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/padron/residentes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vincula una persona a una vivienda como residente (HU-02) */
        post: operations["PadronController_registrarResidente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/padron/vehiculos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra un vehículo; la placa única activa la garantiza la base */
        post: operations["PadronController_registrarVehiculo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/padron/vehiculos/{id}/desactivacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Baja lógica del vehículo; el motivo es obligatorio (RN-19) */
        post: operations["PadronController_desactivarVehiculo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/padron/viviendas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Alta de vivienda; el identificador único activo lo garantiza la base */
        post: operations["PadronController_registrarVivienda"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/padron/viviendas/{id}/desactivacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Baja lógica de la vivienda; conserva su historial (RN-19, CA-02) */
        post: operations["PadronController_desactivarVivienda"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** La aplicación puede atender tráfico */
        get: operations["SaludController_listo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccesosPorHoraDto: {
            /** @description Siempre 24 franjas, incluidas las de cero: el eje lo fija el servidor */
            franjas: components["schemas"]["FranjaDeAccesosDto"][];
            /** @example America/Bogota */
            zonaHoraria: string;
            /** Format: date-time */
            desde: string;
            /** Format: date-time */
            hasta: string;
        };
        AcompananteAgregadoDto: {
            agregado: boolean;
        };
        AgregarAcompananteDto: {
            /**
             * Format: uuid
             * @description El acompañante entra por su PROPIA identidad, para que la lista negra lo alcance (D-01).
             */
            personaId: string;
            nombre: string;
        };
        AlcanceDeCopropiedadesDto: {
            /** @description Las copropiedades que el token alcanza, y solo esas. Para el superadministrador son todas las activas; para un administrador, la suya; para un operador de central, las de su turno. Un arreglo vacío es una respuesta legítima. */
            copropiedades: components["schemas"]["CopropiedadResumenDto"][];
            /** @description true cuando el alcance es global y no viene de una pertenencia concreta (superadministrador). La consola lo usa para explicar por qué puede conmutar. */
            alcanceGlobal: boolean;
        };
        AlertaExpuestaDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            tipo: "lista_negra" | "sabotaje" | "dispositivo_caido" | "acceso_dudoso" | "panico" | "apertura_fallida";
            /** @enum {string} */
            severidad: "informativa" | "media" | "alta" | "critica";
            /** @enum {string} */
            estado: "abierta" | "en_atencion" | "resuelta";
            /** Format: date-time */
            generadaEn: string;
            /** Format: date-time */
            escaladaEn: string | null;
            /** Format: uuid */
            eventoId: string | null;
            /** Format: uuid */
            dispositivoId: string | null;
            /** @description KPI-25 medido, no supuesto: null mientras no se haya escalado */
            escaladaDentroDelPlazo: boolean | null;
            notas: string | null;
        };
        AutorizacionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            viviendaId: string;
            vivienda: string;
            visitante: string;
            documento: string;
            /** Format: date-time */
            desde: string;
            /** Format: date-time */
            hasta: string;
            /** @enum {string} */
            tipo: "unica" | "recurrente";
            /** @enum {string} */
            estado: "activa" | "revocada";
            placa: string | null;
            acompanantes: string[];
            patron: components["schemas"]["PatronDto"] | null;
            /** Format: date-time */
            revocadaEn: string | null;
            motivoRevocacion: string | null;
        };
        AutorizarZonaDto: {
            autorizacionId: string;
        };
        BajaDto: {
            desactivado: boolean;
        };
        CapturarRostroDto: {
            /** @description El TITULAR del dato: el visitante (RN-10) */
            titularId: string;
            autorizacionId?: string;
            medidas: components["schemas"]["MedidasDto"];
            /** @description Vector biométrico en base64. No es la fotografía. */
            vector: string;
            /** @description Versión de la política de tratamiento aceptada */
            versionPolitica: string;
            /** @enum {string} */
            canal: "app" | "sms" | "correo" | "whatsapp" | "presencial";
            /** @description Instante de supresión programada (RN-11) */
            suprimirEn: string;
        };
        CargarPadronDto: {
            /** @description Contenido CSV con cabecera; sin bytes nulos. */
            csv: string;
        };
        CargarPadronXlsxDto: {
            /**
             * Format: byte
             * @description Hoja .xlsx en base64. Se valida el TIPO REAL por firma, nunca la extensión.
             */
            xlsxBase64: string;
        };
        CodigosDeRecuperacionDto: {
            /**
             * @description Códigos de un solo uso, en claro. Se entregan UNA vez: solo se guarda su hash. No dan acceso — autorizan a retirar el factor perdido para inscribir otro.
             * @example [
             *       "A1B2C-D3E4F",
             *       "09876-54321"
             *     ]
             */
            codigos: string[];
            /** @example 10 */
            cantidad: number;
        };
        ConfigurarZonaDto: {
            nombre?: string;
            /** @description Aforo máximo simultáneo (RN-14) */
            aforoMaximo?: number;
            horario?: components["schemas"]["FranjaDto"][];
            /** @enum {string} */
            politicaReinicio?: "cierre_horario" | "manual" | "nunca";
            normas?: string[];
            /** @description Cierre manual del operador, sin presencia física (PB-04) */
            abierta?: boolean;
        };
        ConteoDto: {
            conteo: number;
        };
        ConteosDeAlertasDto: {
            /** @example 3 */
            pendientes: number;
            /**
             * @description Severidad más grave entre las pendientes; null si no hay ninguna
             * @enum {string|null}
             */
            severidadMaxima: "informativa" | "media" | "alta" | "critica" | null;
        };
        ConteosDeVisitantesDto: {
            /**
             * @description Autorizaciones activas que se cruzan con el día local
             * @example 34
             */
            autorizacionesDelDia: number;
            /**
             * @description Ingresos menos salidas del día. Aproximación declarada: una salida puede no registrarse por fallo de sensor (CU-05, excepción 6a). Nunca es negativo.
             * @example 8
             */
            dentroAhora: number;
        };
        ConteosDelPadronDto: {
            /** @example 247 */
            residentesActivos: number;
            /** @example 4 */
            residentesAltaEnVentana: number;
            /** @example 183 */
            vehiculosActivos: number;
            /** @example 12 */
            vehiculosAltaEnVentana: number;
        };
        CopropiedadDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Rol con el que el llamante alcanza esta copropiedad
             * @enum {string}
             */
            alcance: "superadministrador" | "administrador" | "portero" | "operador_central" | "residente" | "servicio";
        };
        CopropiedadResumenDto: {
            /** Format: uuid */
            id: string;
            /** @example Urbanización Mira */
            nombre: string;
            /**
             * @description Decide qué significa «hoy» en el tablero. Viaja con cada copropiedad porque un superadministrador puede conmutar entre husos distintos en la misma sesión.
             * @example America/Bogota
             */
            zonaHoraria: string;
        };
        CrearAutorizacionDto: {
            /** Format: uuid */
            viviendaId: string;
            /**
             * Format: uuid
             * @description Persona que visita.
             */
            personaId: string;
            /** Format: date-time */
            desde: string;
            /** Format: date-time */
            hasta: string;
            zonasPermitidas?: string[];
            maximoAcompanantes?: number;
            /** @description Su presencia es lo único que distingue una recurrente de una única (HU-09). */
            patron?: components["schemas"]["PatronDeEntradaDto"];
        };
        DesactivarDto: {
            /** @description Obligatorio (RN-19). Queda en la auditoría junto al actor y no se puede editar. */
            motivo: string;
        };
        DetalleDeErrorDto: {
            /** @description Un mensaje, o el arreglo que devuelve el ValidationPipe con un renglón por campo rechazado. La consola muestra el arreglo campo a campo; una cadena, tal cual. */
            message: string | string[];
            /** @example Bad Request */
            error?: string;
            /** @example 400 */
            statusCode?: number;
        };
        DispositivoDelTableroDto: {
            /** Format: uuid */
            id: string;
            /** @example Talanquera portería principal */
            nombre: string;
            /** @enum {string} */
            tipo: "camara_lpr" | "terminal_facial" | "rele" | "intercom" | "controlador_io";
            /** Format: uuid */
            zonaId: string | null;
            /** @description IP o FQDN del equipo. Solo se rellena para roles administrativos (C-11); para el resto llega null. NUNCA sale la credencial ni su referencia (RN-21). */
            host: string | null;
            puerto: number | null;
            modelo: string | null;
            firmware: string | null;
            /**
             * @description Derivado del último latido contra el umbral de la copropiedad (migración 0020), no leído de la columna estado_salud, que puede ir por detrás.
             * @enum {string}
             */
            estado: "saludable" | "degradado" | "caido";
            /** Format: date-time */
            ultimoLatido: string | null;
            /** Format: date-time */
            ultimaSincronizacion: string | null;
            segundosSinLatir: number | null;
        };
        ErrorApiDto: {
            /**
             * @description Código HTTP, repetido en el cuerpo
             * @example 404
             */
            estado: number;
            /**
             * @description Identificador de correlación para seguir la petición en la bitácora
             * @example a1b2c3d4
             */
            correlacion: string;
            /** @description Detalle para el cliente en 4xx. En 5xx es siempre «Error interno»: el mensaje original no sale, porque suele llevar nombres de tabla o fragmentos de consulta. */
            mensaje: string | components["schemas"]["DetalleDeErrorDto"];
        };
        ErrorDeFilaDto: {
            fila: number;
            motivo: string;
        };
        EstadoDeDispositivosDto: {
            dispositivos: components["schemas"]["DispositivoDelTableroDto"][];
            /** @example 3 */
            saludables: number;
            /** @example 1 */
            degradados: number;
            /** @example 0 */
            caidos: number;
        };
        EventoIngestaDto: {
            copropiedadId: string;
            dispositivoId: string;
            /** @enum {string} */
            metodo: "placa" | "facial" | "manual" | "remoto" | "tarjeta";
            personaId?: string;
            placaLeida?: string;
            zonaId?: string;
            /** @description Confianza de la lectura, 0..1 */
            confianzaCentesimas: number;
            /** @description Identificador del evento en el equipo (RN-17) */
            referenciaExterna: string;
        };
        EventoRegistradoDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            copropiedadId: string;
            /** Format: date-time */
            ocurridoEn: string;
            /** @enum {string} */
            tipo: "ingreso" | "salida" | "denegado" | "alerta" | "manual";
            /** @enum {string} */
            resultado: "permitido" | "negado";
            /**
             * @description Motivo tipado de la denegación; null cuando el acceso fue permitido. La precedencia del motor (listaNegra > vigencia > patrón > zona) decide cuál se sella.
             * @enum {string|null}
             */
            motivo: "VIGENCIA_EXPIRADA" | "AFORO_SUPERADO" | "LISTA_NEGRA" | "ZONA_NO_AUTORIZADA" | "FUERA_DE_PATRON" | "FUERA_DE_HORARIO" | "SIN_CONSENTIMIENTO" | "PLACA_DESCONOCIDA" | "CONFIANZA_INSUFICIENTE" | "FALLO_TECNICO" | null;
            /** @enum {string} */
            metodo: "placa" | "facial" | "manual" | "remoto" | "tarjeta";
            /** Format: uuid */
            personaId: string | null;
            /** Format: uuid */
            viviendaId: string | null;
            /** Format: uuid */
            zonaId: string | null;
            /** Format: uuid */
            dispositivoId: string;
            /** @example ABC123 */
            placaDetectada: string | null;
            confianza: number | null;
            /** @description Regla que determinó el resultado */
            reglaAplicada: string;
            /** @description Versión de reglas con la que se decidió; hace auditable la decisión del Edge */
            versionReglas: number;
            /** Format: uuid */
            operadorId: string | null;
            motivoManual: string | null;
            /** Format: uuid */
            evidenciaId: string | null;
            /** @description Resuelto localmente por el Edge con caché de reglas (RN-16, CA-21, KPI-31) */
            decididoPorEdge: boolean;
        };
        FilaDeInformeDto: {
            /** Format: date-time */
            momento: string;
            titular: string;
            vivienda: string;
            dispositivo: string;
            /** @description Placa, rostro, tarjeta… (columna MÉTODO del mockup) */
            metodo: string;
            /** @enum {string} */
            resultado: "permitido" | "negado";
            detalle: string;
        };
        FranjaDeAccesosDto: {
            /** @description Hora local de la copropiedad */
            hora: number;
            /** @example 12 */
            permitidos: number;
            /** @example 1 */
            negados: number;
        };
        FranjaDto: {
            /** @description Día 0..6 con domingo = 0. */
            dia: number;
            minutoInicio: number;
            minutoFin: number;
            /** @description La franja viene del día anterior: una zona abierta de 22:00 a 02:00 son DOS franjas encadenadas, no una que reinicia a medianoche. El contador de aforo no se reinicia con el cambio de día (CU-05). */
            continuaDelDiaAnterior: boolean;
        };
        IdAutorizacionDto: {
            /** Format: uuid */
            id: string;
        };
        IdCreadoDto: {
            /** Format: uuid */
            id: string;
        };
        IndicadoresDto: {
            padron: components["schemas"]["ConteosDelPadronDto"];
            visitantes: components["schemas"]["ConteosDeVisitantesDto"];
            alertas: components["schemas"]["ConteosDeAlertasDto"];
            ventana: components["schemas"]["VentanaDelDiaDto"];
        };
        InformeDto: {
            /** @enum {string} */
            tipo: "accesos_por_periodo" | "visitantes_frecuentes" | "uso_de_zonas" | "auditoria_de_sistema";
            /** Format: date-time */
            desde: string;
            /** Format: date-time */
            hasta: string;
            total: number;
            filas: components["schemas"]["FilaDeInformeDto"][];
            frecuencia: components["schemas"]["PuntoDeFrecuenciaDto"][];
            /** @description Se alcanzó el tope de la vista previa; la exportación trae el conjunto completo. */
            truncado: boolean;
            /** @description Limitaciones reales del informe, para mostrarlas en pantalla en vez de fingirlas. */
            notas: string[];
        };
        IngestaAceptadaDto: {
            /** @example true */
            aceptado: boolean;
        };
        IngestaDto: {
            /** Format: uuid */
            copropiedadId: string;
        };
        LatidoDto: {
            copropiedadId: string;
            dispositivoId: string;
        };
        ListoDto: {
            /** @example listo */
            estado: string;
            /**
             * @description Estado por dependencia. Un 503 devuelve esta misma forma con el detalle.
             * @example {
             *       "configuracion": "ok",
             *       "jwks": "ok",
             *       "postgres": "no-conectado-etapa-04"
             *     }
             */
            dependencias: {
                [key: string]: string;
            };
        };
        MedidasDto: {
            rostrosDetectados: number;
            nitidez: number;
            iluminacion: number;
            proporcionRostro: number;
        };
        NotasDeAlertaDto: {
            notas: string;
        };
        PaginaDeEventosDto: {
            filas: components["schemas"]["EventoRegistradoDto"][];
            /** @description Cursor opaco de la siguiente página; null cuando no hay más */
            siguiente: string | null;
        };
        PaginaDeViviendasDto: {
            totales: components["schemas"]["TotalesDeViviendasDto"];
            viviendas: components["schemas"]["ViviendaDto"][];
        };
        PatronDeEntradaDto: {
            /**
             * @description Días de la semana, 0..6 con domingo = 0 (RN-22).
             * @example [
             *       1,
             *       2,
             *       3,
             *       4,
             *       5
             *     ]
             */
            dias: number[];
            /** @example 480 */
            minutoInicio: number;
            /** @example 1080 */
            minutoFin: number;
            /**
             * @description Desfase UTC en minutos de la copropiedad; el patrón es local, no UTC.
             * @example -300
             */
            desplazamientoUtcMinutos: number;
        };
        PatronDto: {
            /** @description Días de la semana, 0..6 con domingo = 0 (el vocabulario del dominio). */
            dias: number[];
            /** @example 08:00 */
            horaInicio: string;
            /** @example 18:00 */
            horaFin: string;
        };
        PendientesDto: {
            /** @description Identificadores de equipos con una orden sin ejecutar: se muestran «sincronizando». */
            dispositivos: string[];
        };
        PermisoDeZonaDto: {
            /** Format: uuid */
            zonaId: string;
        };
        PuntoDeFrecuenciaDto: {
            /** @description Lunes de la semana ISO, YYYY-MM-DD */
            semana: string;
            total: number;
        };
        RecuperacionDeFactorDto: {
            /**
             * @description Factores TOTP verificados que se retiraron. Ya se puede inscribir uno nuevo.
             * @example 1
             */
            factoresRetirados: number;
            /** @description Códigos de recuperación que quedan sin usar */
            codigosRestantes: number;
        };
        RecuperarFactorDto: {
            /**
             * @description Código de recuperación con la forma XXXXX-XXXXX
             * @example A1B2C-D3E4F
             */
            codigo: string;
        };
        RegistrarResidenteDto: {
            /** Format: uuid */
            viviendaId: string;
            /** Format: uuid */
            personaId: string;
            esTitular?: boolean;
            parentesco?: string;
        };
        RegistrarVehiculoDto: {
            /** Format: uuid */
            viviendaId: string;
            /** @example ABC123 */
            placa: string;
            /** Format: uuid */
            personaId?: string;
            marca?: string;
            modelo?: string;
            color?: string;
            /** @enum {string} */
            tipo?: "automovil" | "motocicleta" | "bicicleta" | "otro";
        };
        RegistrarViviendaDto: {
            /** @example Casa 12 */
            identificador: string;
            manzana?: string;
            direccion?: string;
        };
        ReservaDelDiaDto: {
            /** Format: uuid */
            id: string;
            titular: string;
            /** Format: date-time */
            desde: string;
            /** Format: date-time */
            hasta: string;
            personas: number;
        };
        ResponderConsentimientoDto: {
            /** @description true acepta, false rechaza. Lo responde el TITULAR. */
            acepta: boolean;
            /** @description Evidencia de la aceptación (RN-09) */
            evidenciaId?: string;
        };
        RestablecimientoRegistradoDto: {
            /**
             * @description Siempre true; la respuesta es 204 sin cuerpo
             * @example true
             */
            registrado: boolean;
        };
        ResultadoDeCargaDto: {
            aceptadas: number;
            /** @description Errores fila a fila. Si hay uno solo, `aplicada` es falso: la carga es atómica. */
            errores: components["schemas"]["ErrorDeFilaDto"][];
            /** @description Verdadero solo si entró el padrón ENTERO. Una carga a medias no existe (HU-03). */
            aplicada: boolean;
            filasLeidas: number;
        };
        ResultadoDeOperacionDto: {
            encolada: boolean;
            /** @enum {string} */
            operacion: "configuracion" | "sincronizacion" | "reinicio";
            /** @enum {string} */
            estado: "sincronizando";
            detalle: string;
        };
        RevocacionDto: {
            revocada: boolean;
        };
        RevocarAutorizacionDto: {
            motivo: string;
        };
        SaludDto: {
            /** @example vivo */
            estado: string;
            /** Format: date-time */
            momento: string;
        };
        SesionDto: {
            /** Format: uuid */
            usuarioId: string;
            /**
             * @description Rol derivado de los claims, no elegido
             * @enum {string}
             */
            rol: "superadministrador" | "administrador" | "portero" | "operador_central" | "residente" | "servicio";
            /**
             * Format: uuid
             * @description Copropiedad del usuario; null en el operador de central, que atiende varias
             */
            copropiedadId: string | null;
            /** @description Alcance del operador de central, acotado a su turno activo (KPI-35) */
            copropiedadesAtendidas: string[];
            /** @description aal2 en el token. Los roles administrativos no operan sin él (RN-20, CA-25): la consola debe llevar al paso de segundo factor mientras sea false. */
            mfaVerificado: boolean;
        };
        SincronizarPlantillaDto: {
            dispositivoId: string;
        };
        TotalesDeViviendasDto: {
            activas: number;
            inactivas: number;
        };
        UrlDeEvidenciaDto: {
            /** @description URL firmada de vida corta (120 s) al bucket privado. No se cachea ni se persiste: el enlace acaba en el historial del navegador y ahí sigue siendo válido (RN-21). */
            url: string;
        };
        VehiculoDto: {
            /** Format: uuid */
            id: string;
            placa: string;
            marca: string | null;
            modelo: string | null;
            color: string | null;
            /** @enum {string} */
            tipo: "automovil" | "motocicleta" | "bicicleta" | "otro";
            /** @enum {string} */
            estado: "activo" | "inactivo";
            /** Format: uuid */
            viviendaId: string;
            viviendaIdentificador: string;
            /** Format: uuid */
            propietarioId: string | null;
            propietarioNombre: string | null;
        };
        VentanaDelDiaDto: {
            /**
             * Format: date-time
             * @description Medianoche local, inclusive
             */
            desde: string;
            /**
             * Format: date-time
             * @description Medianoche local siguiente, exclusiva
             */
            hasta: string;
            /**
             * @description Zona horaria de la copropiedad con la que se calculó «hoy». Se declara para que la consola no vuelva a interpretarlo con la zona del navegador.
             * @example America/Bogota
             */
            zonaHoraria: string;
        };
        VeredictoDeIngresoDto: {
            admitido: boolean;
            conteo: number | null;
            motivo: string | null;
        };
        ViviendaDto: {
            /** Format: uuid */
            id: string;
            identificador: string;
            manzana: string | null;
            direccion: string | null;
            /** @enum {string} */
            estado: "activo" | "inactivo";
            estadoAdministrativo: string;
            residentes: number;
            vehiculos: number;
            /** @description Autorizaciones vigentes que la vivienda conserva. RN-13: una vivienda inactiva no genera autorizaciones nuevas pero conserva las vigentes. */
            autorizacionesVigentes: number;
            desactivadaEn: string | null;
            motivoDesactivacion: string | null;
        };
        ZonaDto: {
            /** Format: uuid */
            id: string;
            nombre: string;
            tipo: string;
            abierta: boolean;
            politicaReinicio: string;
            normas: string[];
            aforoMaximo: number;
            aforoActual: number;
            aforoDisponible: number;
            dentroDeHorario: boolean;
            aforoCompleto: boolean;
            horario: components["schemas"]["FranjaDto"][];
            /** @description Minutos de desfase UTC del horario de la zona. */
            desplazamientoUtcMinutos: number;
            /** @description Reservas del día. Vacío mientras no exista el módulo de reservas (P-15): la pantalla muestra el estado vacío, que es información honesta, y no un número inventado. */
            reservasDelDia: components["schemas"]["ReservaDelDiaDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AutenticacionController_generarCodigos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodigosDeRecuperacionDto"];
                };
            };
            /** @description 5 por minuto (§2.7.5) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    AutenticacionController_recuperarFactor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecuperarFactorDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecuperacionDeFactorDto"];
                };
            };
            /** @description Código no válido o ya usado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
            /** @description 5 por minuto (§2.7.5) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    AutenticacionController_registrarRestablecimiento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestablecimientoRegistradoDto"];
                };
            };
            /** @description 5 por minuto (§2.7.5) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    AutenticacionController_sesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionDto"];
                };
            };
            /** @description Token ausente, caducado o inválido. También cuando un rol administrativo presenta un token `aal1`: está autenticado, pero no habilitado (RN-20, CA-25). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    CopropiedadesController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlcanceDeCopropiedadesDto"];
                };
            };
        };
    };
    CopropiedadesController_ingerir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestaAceptadaDto"];
                };
            };
            /** @description Copropiedad fuera del alcance */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    CopropiedadesController_leer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopropiedadDto"];
                };
            };
            /** @description 404 y no 403 a propósito: un 403 confirmaría que el identificador existe, y esa confirmación ya permite enumerar recursos ajenos contando respuestas. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    AlertasController_abiertas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertaExpuestaDto"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    AlertasController_atender: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                alertaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertaExpuestaDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
            /** @description La alerta ya está atendida o resuelta */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    AlertasController_resolver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                alertaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotasDeAlertaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertaExpuestaDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    AutorizacionesController_listar: {
        parameters: {
            query?: {
                ver?: "activas" | "historial";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutorizacionDto"][];
                };
            };
        };
    };
    AutorizacionesController_crearAutorizacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearAutorizacionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdAutorizacionDto"];
                };
            };
        };
    };
    AutorizacionesController_agregarAcompanante: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                autorizacionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgregarAcompananteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcompananteAgregadoDto"];
                };
            };
        };
    };
    AutorizacionesController_revocar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                autorizacionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevocarAutorizacionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevocacionDto"];
                };
            };
        };
    };
    BiometriaController_ejecutarBarrido: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BiometriaController_capturarRostro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapturarRostroDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BiometriaController_verConsentimiento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                consentimientoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BiometriaController_responderConsentimiento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                consentimientoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponderConsentimientoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BiometriaController_revocarConsentimiento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                consentimientoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BiometriaController_sincronizarPlantilla: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                plantillaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SincronizarPlantillaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DispositivosController_pendientes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendientesDto"];
                };
            };
        };
    };
    DispositivosController_configurar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                dispositivoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDeOperacionDto"];
                };
            };
        };
    };
    DispositivosController_reiniciar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                dispositivoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDeOperacionDto"];
                };
            };
        };
    };
    DispositivosController_sincronizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                dispositivoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDeOperacionDto"];
                };
            };
        };
    };
    EventosController_historial: {
        parameters: {
            query: {
                /** @description Inicio del rango, ISO-8601 con zona */
                desde: string;
                /** @description Fin del rango, EXCLUIDO */
                hasta: string;
                viviendaId?: string;
                personaId?: string;
                dispositivoId?: string;
                zonaId?: string;
                tipo?: "ingreso" | "salida" | "denegado" | "alerta" | "manual";
                resultado?: "permitido" | "negado";
                motivo?: "VIGENCIA_EXPIRADA" | "AFORO_SUPERADO" | "LISTA_NEGRA" | "ZONA_NO_AUTORIZADA" | "FUERA_DE_PATRON" | "FUERA_DE_HORARIO" | "SIN_CONSENTIMIENTO" | "PLACA_DESCONOCIDA" | "CONFIANZA_INSUFICIENTE" | "FALLO_TECNICO";
                tamanoPagina?: number;
                /** @description Cursor opaco devuelto por la página anterior */
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeEventosDto"];
                };
            };
            /** @description Copropiedad fuera del alcance del token */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    EventosController_exportacion: {
        parameters: {
            query: {
                /** @description Inicio del rango, ISO-8601 con zona */
                desde: string;
                /** @description Fin del rango, EXCLUIDO */
                hasta: string;
                viviendaId?: string;
                personaId?: string;
                dispositivoId?: string;
                zonaId?: string;
                tipo?: "ingreso" | "salida" | "denegado" | "alerta" | "manual";
                resultado?: "permitido" | "negado";
                motivo?: "VIGENCIA_EXPIRADA" | "AFORO_SUPERADO" | "LISTA_NEGRA" | "ZONA_NO_AUTORIZADA" | "FUERA_DE_PATRON" | "FUERA_DE_HORARIO" | "SIN_CONSENTIMIENTO" | "PLACA_DESCONOCIDA" | "CONFIANZA_INSUFICIENTE" | "FALLO_TECNICO";
                tamanoPagina?: number;
                /** @description Cursor opaco devuelto por la página anterior */
                cursor?: string;
                formato: "csv" | "excel" | "pdf";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fichero del informe. La cabecera X-NCR-Truncado dice si está completo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/vnd.ms-excel": string;
                    "application/pdf": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["ErrorApiDto"];
                    "application/vnd.ms-excel": components["schemas"]["ErrorApiDto"];
                    "application/pdf": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    EventosController_flujo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flujo SSE. Temas: «listo» al abrir, «eventos» por cada acceso registrado y «alertas» por cada escalamiento. La carga de cada mensaje es un EventoRegistradoDto o un AlertaExpuestaDto según el tema. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    EventosController_urlDeEvidencia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                eventoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlDeEvidenciaDto"];
                };
            };
            /** @description Sin evidencia, o evento inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorApiDto"];
                };
            };
        };
    };
    InformesController_generar: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
                tipo?: "accesos_por_periodo" | "visitantes_frecuentes" | "uso_de_zonas" | "auditoria_de_sistema";
                viviendaId?: string;
                dispositivoId?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformeDto"];
                };
            };
        };
    };
    PadronDeCopropiedadController_vehiculos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiculoDto"][];
                };
            };
        };
    };
    PadronDeCopropiedadController_viviendas: {
        parameters: {
            query?: {
                estado?: "activo" | "inactivo";
                busqueda?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeViviendasDto"];
                };
            };
        };
    };
    TableroController_leerAccesosPorHora: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccesosPorHoraDto"];
                };
            };
        };
    };
    TableroController_leerDispositivos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoDeDispositivosDto"];
                };
            };
        };
    };
    TableroController_leerIndicadores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicadoresDto"];
                };
            };
        };
    };
    ZonasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonaDto"][];
                };
            };
        };
    };
    ZonasController_permiso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                zonaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutorizarZonaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermisoDeZonaDto"];
                };
            };
        };
    };
    ZonasController_configuracion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                zonaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigurarZonaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonaDto"];
                };
            };
        };
    };
    ZonasController_ingreso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                zonaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VeredictoDeIngresoDto"];
                };
            };
        };
    };
    ZonasController_salida: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                zonaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConteoDto"];
                };
            };
        };
    };
    SaludController_salud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludDto"];
                };
            };
        };
    };
    IngestaController_recibir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventoIngestaDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IngestaController_latido: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LatidoDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PadronController_cargar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CargarPadronDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDeCargaDto"];
                };
            };
        };
    };
    PadronController_cargarXlsx: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CargarPadronXlsxDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDeCargaDto"];
                };
            };
        };
    };
    PadronController_registrarResidente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarResidenteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdCreadoDto"];
                };
            };
        };
    };
    PadronController_registrarVehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarVehiculoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdCreadoDto"];
                };
            };
        };
    };
    PadronController_desactivarVehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesactivarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BajaDto"];
                };
            };
        };
    };
    PadronController_registrarVivienda: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarViviendaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdCreadoDto"];
                };
            };
        };
    };
    PadronController_desactivarVivienda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesactivarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BajaDto"];
                };
            };
        };
    };
    SaludController_listo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListoDto"];
                };
            };
            /** @description Falta una dependencia. El proceso está sano: sacar del balanceador, no reiniciar. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListoDto"];
                };
            };
        };
    };
}
